# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('realese', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('like', models.IntegerField()),
            ],
        ),
    ]
