# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='link',
            field=models.TextField(),
        ),
    ]
