# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import trailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0002_auto_20160728_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trailer',
            name='poster',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=trailer.models.uploaded_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
