# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_auto_20160728_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='poster',
            new_name='image',
        ),
    ]
