# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0005_auto_20160728_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='realese',
        ),
    ]
