# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0006_auto_20160730_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='category',
            field=models.CharField(default=datetime.datetime(2016, 8, 2, 7, 16, 40, 643258, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
