# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0007_trailer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='release',
            field=models.IntegerField(default=2000),
        ),
    ]
