# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0008_trailer_release'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='link',
            new_name='embed_link',
        ),
    ]
